controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.50
  min_vel_x: 0.10
  max_rotational_vel: 50
  max_rot_vel: 10.5
  max_trans_vel: 10.5
  min_in_place_rotational_vel: 10
  acc_lim_th: 0.75
  acc_lim_x: 0.50
  acc_lim_y: 0.50
  escape_vel: -0.3

  holonomic_robot: false
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5
  goal_distance_bias: 0.6
  path_distance_bias: 0.4
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

#robot min/max: -.5,.5