recovery_behaviors: [{name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
                     {name: rotate_recovery, type: rotate_recovery/RotateRecovery},
                     {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
                    # {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},]
#                    {name: move_slow_and_clear, type: move_slow_and_clear/MoveSlowAndClear}]

conservative_reset:
  reset_distance: 0.01

aggressive_reset:
  reset_distance: 0.01

move_slow_and_clear:
  clearing_distance: 0.01
